### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by mdconaway** [sukima/ember-onsenui#2]
The newest version of this library does not appear to be in the NPM repository, and for the most part it appears to be working for my use cases.

Any chance you will be pushing it to NPM soon so that I can remove a github install url from my package.json?

Thanks for all the work on this.  Is there anything I could do to help improve the library?  This library has helped me greatly in making mobile apps with Ember.

**Comment by sukima** [comment]
>The newest version of this library does not appear to be in the NPM repository, and for the most part it appears to be working for my use cases.

I had no idea it was working. I stop development when the onsenui developer kinda didn't understand a fundamental issue directly effecting it's use in Ember or React.

I can release a version to NPM. Are you ok with a version of `0.2.0-alpha` ?

**Comment by mdconaway** [comment]
Yeah, that sounds good to me!

What was the issue you were having with the OnsenUI team?  Is it something we could work around with some clever coding in the addon itself?

**Comment by sukima** [comment]
About a year ago. Onsenui was written so that when the webcomponents are rendered they look at the attribute values to determine how to render. These values become permanent, meaning that if they get changed the webcomponent doesn't update. This was particularly an issue with the input which relied on a hard coded `type` attribute.

In Ember and React and other frameworks when they render a component they first create the component (`var el = document.createElement('component-name')`) and *then* subsequently set the attributes (`el.setAttribute('type', 'password');`). This distinction means that the Onsenui components are required to have these attributes hard coded into the templates code.

I went into great detail on the problem in [this thread](https://github.com/OnsenUI/OnsenUI/issues/1262) and as far as I know (despite the author prematurely closing the ticket) this still has not been fixed. I pretty much gave up on this Ember addon as a result.
